package dk.sep3.dbserver.model.passwordManager.db_entities;

import jakarta.persistence.*;

import java.io.Serializable;
import java.util.Objects;

@Entity // Assigns this class as an Entity for Spring Boot, to use as a base for its Data Persistence interface.
@Table(name="\"master_user\"") // Tells Spring Boot JPA, what the name of this database table is.
public class MasterUser implements Serializable
{
  @Id  // Tells Spring Boot, that this value is the primary key.
  @GeneratedValue (strategy = GenerationType.SEQUENCE, generator = "masteruser_id_generator") // Tells Spring Boot, that the primary key is generated by the database, using a sequence, and defines the specific generator in the database to utilize.
  @SequenceGenerator(name = "masteruser_id_generator", sequenceName = "master_user_id_seq", allocationSize = 1)
  private int id;

  @Column (name = "master_username", nullable=false, unique = true) // Tells Spring Boot, that this variable has a column with the name "masterusername" in the database, and that values in this cannot be null.
  private String masterUsername;

  @Column (name = "master_password", nullable=false) // Tells Spring Boot, that this variable has a column with the name "password" in the database, and that values in this cannot be null.
  private String encryptedPassword;

  // A no-args constructor, as required by the Java Data API (JPA) specifications.
  protected MasterUser() {
  }

  public MasterUser(int id, String masterUsername, String encryptedPassword) {
    setId(id);
    setMasterUsername(masterUsername);
    setEncryptedPassword(encryptedPassword);
  }

  public int getId() {
    return id;
  }

  public void setId(int id) {
    this.id = id;
  }

  public String getMasterUsername() {
    return masterUsername;
  }

  public void setMasterUsername(String masterUsername) {
    this.masterUsername = masterUsername;
  }

  public String getEncryptedPassword() {
    return encryptedPassword;
  }

  public void setEncryptedPassword(String password) {
    this.encryptedPassword = password;
  }

  // Required by Spring Boot JPA:

  @Override public boolean equals(Object o) {
    if (this == o)
      return true;
    if (o == null || getClass() != o.getClass())
      return false;
    MasterUser masterUser = (MasterUser) o;
    return getId() == masterUser.getId() && Objects.equals(getMasterUsername(), masterUser.getMasterUsername()) && Objects.equals(getEncryptedPassword(), masterUser.getEncryptedPassword());
  }

  // Required by Spring Boot JPA:
  @Override public int hashCode() {
    return Objects.hash(getId(), getMasterUsername(), getEncryptedPassword());
  }

  @Override public String toString() {
    return "MasterUser{" + "id='" + id + "'" + "masterUsername='" + masterUsername + '\'' + ", password='" + encryptedPassword + '\'' + '}';
  }
}
